dependencies:
- python=3.11
- pip
- pip:
  - transformers==4.36.1
  - pandas==2.0.0
  - requests==2.31.0
  - ipykernel==6.27.1
  - torch==2.1.2
  - torchvision==0.16.2
  - azureml-mlflow==1.54.0.post1
  - mlflow==2.9.2
name: rest-api-demo-env
